name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  fixtures:
    name: fixtures-up-to-date
    runs-on: ubuntu-latest
    # This job appears to be non-deterministic.
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build fixtures
      run: bash -c 'cd test/testdata && ./build-fixtures.go'
    - name: Diff fixtures
      run: git diff --exit-code test/testdata

  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        go: [ '1.19', '1.20' ]
    runs-on: ${{ matrix.os }}

    name: Build (Go ${{ matrix.go }}, OS ${{ matrix.os }})
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: go test -race -bench='.+' -v ./...
      run: go test -race -bench='.+' -v ./...
